[package]
name = "uncx-substream"
version = "0.1.0"
edition = "2021"

[lib]
name = "uncx_substream"
crate-type = ["lib", "cdylib"]

[dependencies]
substreams = "^0.5.0"
substreams-solana = { git = "https://github.com/streamingfast/substreams-solana", branch = "master" }
substreams-database-change = "1.0.0"
substreams-solana-raydium-amm = { git = "https://github.com/0xpapercut/substreams-solana-raydium-amm", branch = "main" }
substreams-solana-structured-instructions = { git = "https://github.com/0xpapercut/substreams-solana-structured-instructions", branch = "main" }
substreams-solana-utils = { git = "https://github.com/0xpapercut/substreams-solana-utils", branch = "main" }
spl-token-substream = { git = "https://github.com/0xpapercut/spl-token-substream", rev = "696500d8c615b02310b8b4387cf5b02b1fb9fd70" }
prost = "0.11"
bs58 = "0.5.0"
uncx-solana-lp-locker = { path = "../solana-lp-locker-monorepo/programs/uncx-solana-lp-locker" }
prost-types = "0.11"
anchor-lang="0.30.0"
base64 = "0.22.1"

[profile.release]
lto = true
opt-level = 's' 
strip = "debuginfo"
